# Generated by Django 4.1.3 on 2022-11-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=255)),
                ('user_lastname', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_username', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_photo', models.CharField(max_length=255)),
                ('user_type', models.IntegerField(max_length=4)),
                ('user_level_access', models.IntegerField(max_length=4)),
                ('user_is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=255)),
                ('customer_lastname', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_username', models.CharField(max_length=255)),
                ('customer_password', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_company', models.CharField(max_length=255)),
                ('customer_vat_no', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(max_length=11)),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_content', models.CharField(max_length=255)),
                ('contact_customer', models.CharField(max_length=255)),
                ('contact_datetime', models.DateTimeField()),
                ('contact_channel', models.CharField(max_length=255)),
                ('contact_files', models.DateField()),
                ('contact_due_date', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.user')),
            ],
        ),
    ]
