# Generated by Django 4.1.3 on 2022-12-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contact_contact_id_alter_user_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('message_title', models.CharField(max_length=255)),
                ('message_content', models.CharField(max_length=255)),
                ('message_customer', models.CharField(max_length=255)),
                ('message_datetime', models.DateTimeField()),
                ('message_channel', models.CharField(max_length=255)),
                ('message_files', models.DateField()),
                ('message_due_date', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.user')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_channel',
            new_name='contact_address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_content',
            new_name='contact_company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_customer',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_due_date',
            new_name='contact_firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_title',
            new_name='contact_lastname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_datetime',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_files',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_mobile',
            field=models.CharField(default='6978888888', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(default='21057888888', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_vat_no',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
