# Generated by Django 4.1.3 on 2022-12-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_lastname',
        ),
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_vat_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
