# Generated by Django 4.1.3 on 2022-12-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_message_message_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
