# Generated by Django 4.1.3 on 2022-12-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_user_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_files',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_file_name', models.CharField(max_length=255)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.message')),
            ],
        ),
    ]
