# Generated by Django 4.1.3 on 2022-12-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_message_message_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
